#!/bin/bash
source config

pushd ~
for i in $(seq 1 ${NUM_PVS}); do
  sudo rm -rf /nfsvolumes/pv0${i}/*
  sudo rm -rf /nfsvolumes/pv0${i}/.a*
  oc export pv pv0${i} > pv
  oc delete pv pv0${i}
  oc create -f pv
  rm -f pv
done
popd
